---
  project_name: "Embioptera Species File"
  project_citation: "Michael D. Maehr & Heidi Hopkins. Embioptera Species File. Version 5.0/5.0. [retrieval date]. <http://Embioptera.SpeciesFile.org>"
  project_authors: "Maehr M.D. & Hopkins, H."
  project_url: "https://embioptera.speciesfile.org'."
  project_old_url: "https://embioptera.archive.speciesfile.org'." 
  focal_taxon: "embioptera"
  focal_taxon_common_name: "webspinners"
  contact_email: "cockroachdoc@gmail.com"
