---
  project_name: "Embioptera Species File"
  project_citation: "Embioptera Species File"
  project_authors: "Hopkins, H."
  project_url: "https://embioptera.speciesfile.org'."
  project_old_url: "http://embioptera.archive.speciesfile.org'." 
  focal_taxon: "embioptera"
  focal_taxon_common_name: "webspinners"
  contact_email: "cockroachdoc@gmail.com"
